/* Auto-generated by genmsg_cpp for file /home/udit/ros_ws/vicon_reader/msg/CoordData.msg */
#ifndef VICON_READER_MESSAGE_COORDDATA_H
#define VICON_READER_MESSAGE_COORDDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace vicon_reader
{
template <class ContainerAllocator>
struct CoordData_ {
  typedef CoordData_<ContainerAllocator> Type;

  CoordData_()
  : frame(0)
  , name()
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , heading(0.0)
  , time(0)
  , latency(0.0)
  {
  }

  CoordData_(const ContainerAllocator& _alloc)
  : frame(0)
  , name(_alloc)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , heading(0.0)
  , time(0)
  , latency(0.0)
  {
  }

  typedef int32_t _frame_type;
  int32_t frame;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef double _heading_type;
  double heading;

  typedef int64_t _time_type;
  int64_t time;

  typedef double _latency_type;
  double latency;


  typedef boost::shared_ptr< ::vicon_reader::CoordData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vicon_reader::CoordData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CoordData
typedef  ::vicon_reader::CoordData_<std::allocator<void> > CoordData;

typedef boost::shared_ptr< ::vicon_reader::CoordData> CoordDataPtr;
typedef boost::shared_ptr< ::vicon_reader::CoordData const> CoordDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::vicon_reader::CoordData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::vicon_reader::CoordData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace vicon_reader

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vicon_reader::CoordData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vicon_reader::CoordData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vicon_reader::CoordData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "febb9c6d91e65dd5b5edb7908d443d6e";
  }

  static const char* value(const  ::vicon_reader::CoordData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfebb9c6d91e65dd5ULL;
  static const uint64_t static_value2 = 0xb5edb7908d443d6eULL;
};

template<class ContainerAllocator>
struct DataType< ::vicon_reader::CoordData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vicon_reader/CoordData";
  }

  static const char* value(const  ::vicon_reader::CoordData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vicon_reader::CoordData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 frame\n\
string name\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 heading\n\
int64 time\n\
float64 latency \n\
\n\
";
  }

  static const char* value(const  ::vicon_reader::CoordData_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vicon_reader::CoordData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.frame);
    stream.next(m.name);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.heading);
    stream.next(m.time);
    stream.next(m.latency);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CoordData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vicon_reader::CoordData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::vicon_reader::CoordData_<ContainerAllocator> & v) 
  {
    s << indent << "frame: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frame);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "time: ";
    Printer<int64_t>::stream(s, indent + "  ", v.time);
    s << indent << "latency: ";
    Printer<double>::stream(s, indent + "  ", v.latency);
  }
};


} // namespace message_operations
} // namespace ros

#endif // VICON_READER_MESSAGE_COORDDATA_H

